docker_builder:
  name: devel-images

  # task run timeout
  timeout_in: 120m

  env:
    DOCKER_USERNAME: ENCRYPTED[5efbccf60cc0d01c4439f21ba4cf0ce86ac44bccb612d47dc4fe5a0fc0b0326de6e06ffe55d39e319ca5cab91e974a7b]
    DOCKER_PASSWORD: ENCRYPTED[e44e13a94c21426c2facb3db84aecc0cd12eaf673917a4fcbe4d06a76dc3efb1b4fa139e6f318393f499d050cb666e03]

  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap

  build_script: |
    docker buildx build \
      --push \
      --platform linux/amd64,linux/arm64 \
      --tag polardb/polardb_pg_devel:centos7 \
      --tag polardb/polardb_pg_devel:latest \
      --file Dockerfile-devel-centos7 .

# docker_builder:
#   name: instance-images
#   depends_on: devel-images

#   # task run timeout
#   timeout_in: 120m

#   env:
#     DOCKER_USERNAME: ENCRYPTED[5efbccf60cc0d01c4439f21ba4cf0ce86ac44bccb612d47dc4fe5a0fc0b0326de6e06ffe55d39e319ca5cab91e974a7b]
#     DOCKER_PASSWORD: ENCRYPTED[e44e13a94c21426c2facb3db84aecc0cd12eaf673917a4fcbe4d06a76dc3efb1b4fa139e6f318393f499d050cb666e03]
#     CIRRUS_CLONE_SUBMODULES: true

#   login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

#   setup_script:
#     - docker buildx create --name multibuilder
#     - docker buildx use multibuilder
#     - docker buildx inspect --bootstrap

#   matrix:
#     -
#       name: single-node-image
#       build_script: |
#         docker buildx build \
#           --push \
#           --platform linux/amd64,linux/arm64 \
#           --tag polardb/polardb_pg_local_instance:single \
#           --file Dockerfile-local-instance-single .
#     -
#       name: withrep-node-image
#       build_script: |
#         docker buildx build \
#           --push \
#           --platform linux/amd64,linux/arm64 \
#           --tag polardb/polardb_pg_local_instance:withrep \
#           --file Dockerfile-local-instance-withrep .
#     -
#       name: htap-node-image
#       build_script: |
#         docker buildx build \
#           --push \
#           --platform linux/amd64,linux/arm64 \
#           --tag polardb/polardb_pg_local_instance:htap \
#           --file Dockerfile-local-instance-htap .
#     -
#       name: binary-image-local
#       build_script: |
#         docker buildx build \
#           --push \
#           --platform linux/amd64,linux/arm64 \
#           --tag polardb/polardb_pg_binary:local \
#           --file Dockerfile-binary-local .
#     -
#       name: binary-image-pfsd
#       build_script: |
#         docker buildx build \
#           --push \
#           --platform linux/amd64,linux/arm64 \
#           --tag polardb/polardb_pg_binary:pfsd \
#           --tag polardb/polardb_pg_binary:latest \
#           --file Dockerfile-binary-pfsd .
