FROM polardb/polardb_pg_devel:ubuntu22.04 AS building
LABEL maintainer="mrdrivingduck@gmail.com"

# Copy source code
WORKDIR /home/postgres/
COPY ./PolarDB-for-PostgreSQL ./PolarDB-for-PostgreSQL

# Compile and install PolarDB-PG
USER root
WORKDIR /home/postgres/PolarDB-for-PostgreSQL
RUN ./build.sh --ec="--prefix=/u01/polardb_pg/ --with-pfsd" --debug=off --ni --port=5432

FROM polardb/polardb_pg_devel:ubuntu22.04
LABEL maintainer="mrdrivingduck@gmail.com"

# Copy binary
COPY --from=building /u01/polardb_pg/ /u01/polardb_pg/

RUN sudo chown -R postgres:postgres /u01/polardb_pg/
RUN sudo chmod -R 700 /u01/polardb_pg/

ENV PATH="/u01/polardb_pg/bin:$PATH"
