FROM debian:11

ARG TARGETARCH
LABEL maintainer="mrdrivingduck@gmail.com"

COPY misc/pg_bsd_indent_$TARGETARCH /usr/bin/pg_bsd_indent

CMD bash

ENV PATH="/home/postgres/tmp_polardb_pg_17_base/bin:/home/postgres/tmp_polardb_pg_16_base/bin:/home/postgres/tmp_polardb_pg_15_base/bin:/home/postgres/tmp_basedir_polardb_pg_1100_bld/bin:$PATH"

# Timezone problem
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Upgrade softwares
RUN apt update -y && \
    apt upgrade -y && \
    apt clean -y

# GCC (force 10) and LLVM (force 16)
RUN apt install -y \
        gcc-10 \
        g++-10 \
        llvm-16-dev \
        clang-16 \
        make \
        gdb \
        pkg-config \
        locales && \
    update-alternatives --install \
        /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave \
        /usr/bin/g++ g++ /usr/bin/g++-10 && \
    update-alternatives --install \
        /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-16 60 --slave \
        /usr/bin/clang++ clang++ /usr/bin/clang++-16 --slave \
        /usr/bin/clang clang /usr/bin/clang-16 && \
    apt clean -y
# Generate locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    sed -i '/zh_CN/s/^# //g' /etc/locale.gen && \
    locale-gen

# Dependencies
RUN DEBIAN_FRONTEND=noninteractive \
    apt install -y \
        bison \
        flex \
        gettext \
        krb5-admin-server \
        krb5-kdc \
        krb5-user \
        libaio-dev \
        libdbi-perl \
        libexpect-perl \
        libfile-find-rule-perl \
        libfuse-dev \
        libgss-dev \
        libicu-dev \
        libipc-run-perl \
        libkrb5-dev \
        libldap2-dev \
        liblz4-dev \
        libpam0g-dev \
        libperl-dev \
        libreadline-dev \
        libssl-dev \
        libunwind-dev \
        libxerces-c-dev \
        libxml2-dev \
        libxslt1-dev \
        python3-dev \
        python3-distutils-extra \
        tcl-dev \
        uuid-dev \
        && \
    apt clean -y

# Tools
RUN apt install -y \
        autoconf \
        iproute2 \
        wget \
        ccache \
        sudo \
        vim \
        git \
        cmake && \
    apt clean -y

# PostGIS
RUN apt install -y \
        libgeos-dev \
        libproj-dev \
        libgdal-dev \
        libprotobuf-c-dev \
        protobuf-compiler \
        protobuf-c-compiler && \
    apt clean -y

# install perl module for TAP test
RUN perl -MCPAN -e "CPAN::Shell->notest('install', 'SHANCOCK/Perl-Tidy-20230309.tar.gz')"

# set to empty if GitHub is not barriered
# ENV GITHUB_PROXY=https://ghproxy.com/
ENV GITHUB_PROXY=

ENV ZLOG_VERSION=1.2.14
ENV PFSD_VERSION=pfsd4pg-release-1.2.42-20220419

# install dependencies from GitHub mirror
RUN cd /usr/local && \
    # zlog for PFSD
    wget --no-verbose --no-check-certificate "${GITHUB_PROXY}https://github.com/HardySimpson/zlog/archive/refs/tags/${ZLOG_VERSION}.tar.gz" && \
    # PFSD
    wget --no-verbose --no-check-certificate "${GITHUB_PROXY}https://github.com/ApsaraDB/PolarDB-FileSystem/archive/refs/tags/${PFSD_VERSION}.tar.gz" && \
    # unzip and install zlog
    gzip -d $ZLOG_VERSION.tar.gz && \
    tar xpf $ZLOG_VERSION.tar && \
    cd zlog-$ZLOG_VERSION && \
    make && make install && \
    echo '/usr/local/lib' >> /etc/ld.so.conf && ldconfig && \
    cd .. && \
    rm -rf $ZLOG_VERSION* && \
    rm -rf zlog-$ZLOG_VERSION && \
    # unzip and install PFSD
    gzip -d $PFSD_VERSION.tar.gz && \
    tar xpf $PFSD_VERSION.tar && \
    cd PolarDB-FileSystem-$PFSD_VERSION && \
    sed -i 's/-march=native //' CMakeLists.txt && \
    ./autobuild.sh && ./install.sh && \
    cd .. && \
    rm -rf $PFSD_VERSION* && \
    rm -rf PolarDB-FileSystem-$PFSD_VERSION*

# create default user
ENV USER_NAME=postgres
RUN echo "create default user" && \
    groupadd -r $USER_NAME && \
    useradd -u 1000 -ms /bin/bash -g $USER_NAME $USER_NAME -p '' && \
    usermod -aG sudo $USER_NAME

# modify conf
RUN echo "modify conf" && \
    mkdir -p /var/log/pfs && chown $USER_NAME /var/log/pfs && \
    mkdir -p /var/run/pfs && chown $USER_NAME /var/run/pfs && \
    mkdir -p /var/run/pfsd && chown $USER_NAME /var/run/pfsd && \
    mkdir -p /dev/shm/pfsd && chown $USER_NAME /dev/shm/pfsd && \
    touch /var/run/pfsd/.pfsd && \
    echo "ulimit -c unlimited" >> /home/postgres/.bashrc && \
    echo "export PGHOST=127.0.0.1" >> /home/postgres/.bashrc && \
    echo "export PATH=/home/postgres/tmp_polardb_pg_15_base/bin:\$PATH" >> /home/postgres/.bashrc && \
    echo "export PATH=/home/postgres/tmp_polardb_pg_16_base/bin:\$PATH" >> /home/postgres/.bashrc && \
    echo "export PATH=/home/postgres/tmp_polardb_pg_17_base/bin:\$PATH" >> /home/postgres/.bashrc && \
    echo 'done'

WORKDIR /home/$USER_NAME
USER $USER_NAME
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
