ARG binary_image_tag=

FROM polardb/polardb_pg_binary:${binary_image_tag}
LABEL maintainer="mrdrivingduck@gmail.com"

ENV PATH="/u01/polardb_pg/bin:$PATH"
ENV POLARDB_USER=
ENV POLARDB_PASSWORD=
ENV POLARDB_PORT=
ENV POLARDB_DATA_DIR=/var/polardb
ENV PGHOST=127.0.0.1

VOLUME ${POLARDB_DATA_DIR}
CMD [ "postgres" ]

WORKDIR /home/postgres/
COPY ./docker-entrypoint.sh ./docker-entrypoint.sh

ENTRYPOINT [ "./docker-entrypoint.sh" ]
