FROM polardb/polardb_pg_devel:ubuntu20.04 AS building

LABEL maintainer="mrdrivingduck@gmail.com"

WORKDIR /home/postgres/

COPY ./PolarDB-for-PostgreSQL ./PolarDB-for-PostgreSQL

WORKDIR /home/postgres/PolarDB-for-PostgreSQL

RUN sudo chown -R postgres:postgres ./

RUN ./polardb_build.sh --withrep --repnum=1

WORKDIR /home/postgres

RUN wget --no-verbose https://download.osgeo.org/postgis/source/postgis-3.3.2.tar.gz && \
    tar -zxf postgis-3.3.2.tar.gz && \
    cd postgis-3.3.2 && \
    ./configure -q && \
    make -s && \
    make -s install

FROM polardb/polardb_pg_devel:ubuntu20.04

LABEL maintainer="mrdrivingduck@gmail.com"

COPY --from=building /home/postgres/tmp_basedir_polardb_pg_1100_bld/ /home/postgres/tmp_basedir_polardb_pg_1100_bld/
COPY --from=building /home/postgres/tmp_datadir_polardb_pg_1100_bld/ /home/postgres/tmp_datadir_polardb_pg_1100_bld/
COPY --from=building /home/postgres/tmp_master_dir_polardb_pg_1100_bld/ /home/postgres/tmp_master_dir_polardb_pg_1100_bld/
COPY --from=building /home/postgres/tmp_replica_dir_polardb_pg_1100_bld/ /home/postgres/tmp_replica_dir_polardb_pg_1100_bld/

RUN sudo chown -R postgres:postgres /home/postgres/tmp_*
RUN sudo chmod -R 700 /home/postgres/tmp_*

ENTRYPOINT \
    ~/tmp_basedir_polardb_pg_1100_bld/bin/pg_ctl -D ~/tmp_master_dir_polardb_pg_1100_bld start && \
    ~/tmp_basedir_polardb_pg_1100_bld/bin/pg_ctl -D ~/tmp_replica_dir_polardb_pg_1100_bld start && \
    bash
