FROM polardb/polardb_pg_binary:latest
LABEL maintainer="mrdrivingduck@gmail.com"

ENV PATH="/home/postgres/tmp_basedir_polardb_pg_1100_bld/bin:$PATH"
ENV POLARDB_USER=
ENV POLARDB_PASSWORD=
ENV POLARDB_PORT=
ENV POLARDB_DATA_DIR=/var/polardb
ENV PGHOST=127.0.0.1

VOLUME ${POLARDB_DATA_DIR}
CMD [ "postgres" ]

WORKDIR /home/postgres/
COPY ./docker-entrypoint.sh ./docker-entrypoint.sh

ENTRYPOINT [ "./docker-entrypoint.sh" ]
