FROM polardb/polardb_pg_binary:localfs

LABEL maintainer="mrdrivingduck@gmail.com"

ENV PATH="/home/postgres/tmp_basedir_polardb_pg_1100_bld/bin:$PATH"
ENV PGPORT=5432
ENV POLARDB_DATA_DIR=/var/polardb

VOLUME ${POLARDB_DATA_DIR}
EXPOSE 5432
CMD [ "psql", "-h", "127.0.0.1" ]

WORKDIR /home/postgres/
COPY ./docker-entrypoint.sh ./docker-entrypoint.sh

ENTRYPOINT [ "./docker-entrypoint.sh" ]
