FROM centos:centos7

LABEL maintainer="mrdrivingduck@gmail.com"

CMD bash

# avoid missing locale problem
RUN sed -i 's/override_install_langs/# &/' /etc/yum.conf

# add EPEL and scl source
RUN rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && \
    yum install -y epel-release centos-release-scl && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo && \
    yum update -y && \
    yum clean all

# GCC and LLVM
RUN yum install -y \
        devtoolset-9-gcc \
        devtoolset-9-gcc-c++ \
        devtoolset-9-gdb \
        devtoolset-9-libstdc++-devel \
        devtoolset-9-make \
        llvm-toolset-7.0-llvm-devel \
        llvm-toolset-7.0-clang-devel \
        cmake3 && \
    yum clean all

# dependencies
RUN yum install -y \
        libicu-devel \
        pam-devel \
        readline-devel \
        libxml2-devel \
        libxslt-devel \
        openldap-devel \
        openldap-clients \
        openldap-servers \
        libuuid-devel \
        xerces-c-devel \
        bison \
        flex \
        gettext \
        tcl-devel \
        python-devel \
        perl-IPC-Run \
        perl-Expect \
        perl-Test-Simple \
        perl-DBD-Pg \
        perl-ExtUtils-Embed \
        perl-ExtUtils-MakeMaker \
        zlib-devel \
        krb5-devel \
        krb5-workstation \
        krb5-server \
        protobuf-devel \
        libaio-devel \
        fuse-devel && \
    ln /usr/lib64/perl5/CORE/libperl.so /usr/lib64/libperl.so && \
    yum clean all

# install basic tools
RUN yum install -y \
        git lcov psmisc sudo vim \
        less  \
        net-tools  \
        python2-psycopg2 \
        python2-requests  \
        tar  \
        shadow-utils \
        which  \
        binutils\
        libtool \
        perf  \
        make sudo \
        wget \
        util-linux && \
    yum clean all

# set to empty if GitHub is not barriered
# ENV GITHUB_PROXY=https://ghproxy.com/
ENV GITHUB_PROXY=

ENV ZLOG_VERSION=1.2.14
ENV OPENSSL_VERSION=OpenSSL_1_1_1k
ENV PFSD_VERSION=pfsd4pg-release-1.2.42-20220419

# install dependencies from GitHub mirror
RUN cd /usr/local && \
    # zlog for PFSD
    wget --no-verbose --no-check-certificate "${GITHUB_PROXY}https://github.com/HardySimpson/zlog/archive/refs/tags/${ZLOG_VERSION}.tar.gz" && \
    # PFSD
    wget --no-verbose --no-check-certificate "${GITHUB_PROXY}https://github.com/ApsaraDB/PolarDB-FileSystem/archive/refs/tags/${PFSD_VERSION}.tar.gz" && \
    # OpenSSL 1.1.1
    wget --no-verbose --no-check-certificate "${GITHUB_PROXY}https://github.com/openssl/openssl/archive/refs/tags/${OPENSSL_VERSION}.tar.gz" && \
    # enable build tools
    echo "source /opt/rh/devtoolset-9/enable" >> /etc/bashrc && \
    echo "source /opt/rh/llvm-toolset-7.0/enable" >> /etc/bashrc && \
    ln -s /usr/bin/cmake3 /usr/bin/cmake && \
    source /etc/bashrc && \
    # unzip and install zlog
    gzip -d $ZLOG_VERSION.tar.gz && \
    tar xpf $ZLOG_VERSION.tar && \
    cd zlog-$ZLOG_VERSION && \
    make && make install && \
    echo '/usr/local/lib' >> /etc/ld.so.conf && ldconfig && \
    cd .. && \
    rm -rf $ZLOG_VERSION* && \
    rm -rf zlog-$ZLOG_VERSION && \
    # unzip and install PFSD
    gzip -d $PFSD_VERSION.tar.gz && \
    tar xpf $PFSD_VERSION.tar && \
    cd PolarDB-FileSystem-$PFSD_VERSION && \
    sed -i 's/-march=native //' CMakeLists.txt && \
    ./autobuild.sh && ./install.sh && \
    cd .. && \
    rm -rf $PFSD_VERSION* && \
    rm -rf PolarDB-FileSystem-$PFSD_VERSION* && \
    # unzip and install OpenSSL 1.1.1
    gzip -d $OPENSSL_VERSION.tar.gz && \
    tar xpf $OPENSSL_VERSION.tar && \
    cd openssl-$OPENSSL_VERSION && \
    ./config --prefix=/usr/local/openssl && make -j8 && make install && \
    cp /usr/local/openssl/lib/lib* /usr/local/lib/ && \
    cp -r /usr/local/openssl/include/openssl /usr/local/include/ && \
    cd .. && \
    rm -rf $OPENSSL_VERSION* && \
    rm -rf openssl-$OPENSSL_VERSION && \
    ldconfig

# add software repository of Node.js LTS
# @see https://github.com/nodesource/distributions
# use yarn for documentation development
RUN curl -fsSL https://rpm.nodesource.com/setup_16.x | bash - && \
    curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    yum install -y yarn && \
    yum clean all

# create default user
ENV USER_NAME=postgres
RUN echo "create default user" && \
    groupadd -r $USER_NAME && \
    useradd -g $USER_NAME $USER_NAME -p '' && \
    usermod -aG wheel $USER_NAME

WORKDIR /home/$USER_NAME

# modify conf
RUN echo "modify conf" && \
    mkdir -p /var/log/pfs && chown $USER_NAME /var/log/pfs && \
    mkdir -p /var/run/pfs && chown $USER_NAME /var/run/pfs && \
    mkdir -p /var/run/pfsd && chown $USER_NAME /var/run/pfsd && \
    mkdir -p /dev/shm/pfsd && chown $USER_NAME /dev/shm/pfsd && \
    touch /var/run/pfsd/.pfsd && \
    chkconfig --add pfsd_env && \
    echo "ulimit -c unlimited" >> /home/postgres/.bashrc && \
    echo "export PATH=/home/postgres/tmp_basedir_polardb_pg_1100_bld/bin:\$PATH" >> /home/postgres/.bashrc && \
    echo "export PGHOST=127.0.0.1" >> /home/postgres/.bashrc && \
    echo "alias pg='psql -h /home/postgres/tmp_master_dir_polardb_pg_1100_bld/'" >> /home/postgres/.bashrc && \
    rm /etc/localtime && \
    cp /usr/share/zoneinfo/UTC /etc/localtime && \
    sed -i 's/4096/unlimited/g' /etc/security/limits.d/20-nproc.conf && \
    sed -i 's/vim/vi/g' /root/.bashrc

USER $USER_NAME
