ARG binary_image_tag=

FROM registry.cn-hangzhou.aliyuncs.com/polardb_pg/polardb_pg_local_instance:${binary_image_tag}

USER root
# https://developer.aliyun.com/article/1122234 

# install certificates
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates libprotobuf-dev \
    libtiff-dev libcurl4-openssl-dev libxml2-dev \
    libjsoncpp-dev libjson-c-dev \
    && rm -rf /var/lib/apt/lists/*

# sudo yum install -y libtiff-devel libcurl-devel libxml2-devel json-c-devel 

# geos
RUN mkdir -p /tmp/downloads && \
wget -t 0 -c -q -O /tmp/downloads/geos-3.11.4.tar.bz2 https://download.osgeo.org/geos/geos-3.11.4.tar.bz2 && \
cd /tmp/downloads && \
tar -xvf geos-3.11.4.tar.bz2 && \
cd geos-3.11.4 && mkdir build  && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..  && make -j 12 &&  make install  && rm /tmp/downloads -rf && \
# add  
echo "/usr/local/lib64" >> /etc/ld.so.conf && \
sudo ldconfig  


# SQLite3
RUN mkdir -p /tmp/downloads && \
wget -t 0 -c -q -O /tmp/downloads/sqlite-autoconf-3400000.tar.gz https://www.sqlite.org/2022/sqlite-autoconf-3400000.tar.gz && \
cd /tmp/downloads && \
tar -xvf sqlite-autoconf-3400000.tar.gz && \
cd sqlite-autoconf-3400000 && ./configure && make -j 12 && make install  && \
rm /tmp/downloads -rf && \
# add  
echo "/usr/local/lib" >> /etc/ld.so.conf && \
sudo ldconfig 

# proj
RUN mkdir -p /tmp/downloads && \
wget -t 0 -c -q -O /tmp/downloads/proj-9.1.1.tar.gz https://download.osgeo.org/proj/proj-9.1.1.tar.gz && \
cd /tmp/downloads && \
tar -xvf proj-9.1.1.tar.gz && \
cd proj-9.1.1 && mkdir build && cd build && cmake .. && make -j 12 &&  make install && \
rm /tmp/downloads -rf


# gdal
RUN mkdir -p /tmp/downloads && \
wget -t 0 -c -q -O /tmp/downloads/gdal-3.6.1.tar.gz https://github.com/OSGeo/gdal/releases/download/v3.6.1/gdal-3.6.1.tar.gz  && \
cd /tmp/downloads && \
tar -xvf gdal-3.6.1.tar.gz && \
cd gdal-3.6.1  && mkdir build && cd build && cmake .. && \
make -j 12 && make install && \
rm /tmp/downloads -rf


# protobuf and protobuf-c
RUN mkdir -p /tmp/downloads && \
wget -t 0 -c -q -O /tmp/downloads/protobuf-all-3.11.4.tar.gz https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protobuf-all-3.11.4.tar.gz && \
cd /tmp/downloads && \
tar -xvf protobuf-all-3.11.4.tar.gz && \
cd protobuf-3.11.4  && ./configure --prefix=/usr/local/protobuf && \
make -j 12 && make install && \
echo "/usr/local/protobuf/lib" >> /etc/ld.so.conf && ldconfig && \
rm /tmp/downloads -rf

# protobuf-c
ENV PATH=/usr/local/protobuf/bin:$PATH
ENV PKG_CONFIG_PATH=/usr/local/protobuf/lib/pkgconfig:$PKG_CONFIG_PATH

RUN mkdir -p /tmp/downloads && \
wget -t 0 -c -q -O /tmp/downloads/protobuf-c-1.3.3.tar.gz https://github.com/protobuf-c/protobuf-c/releases/download/v1.3.3/protobuf-c-1.3.3.tar.gz && \
cd /tmp/downloads && \
tar -xvf protobuf-c-1.3.3.tar.gz && \
cd protobuf-c-1.3.3  && ./configure --prefix=/usr/local/protobuf-c && \
make -j 12 && make install && \
echo "/usr/local/protobuf-c/lib" >> /etc/ld.so.conf && ldconfig && \
rm /tmp/downloads -rf

# postgis
ENV PKG_CONFIG_PATH=/usr/local/protobuf-c/lib/pkgconfig:/usr/local/protobuf/lib/pkgconfig:$PKG_CONFIG_PATH  
ENV PATH=/usr/local/protobuf-c/bin:/usr/local/protobuf/bin:$PATH

RUN mkdir -p /tmp/downloads && \
wget -t 0 -c -q -O /tmp/downloads/postgis-3.3.2.tar.gz https://download.osgeo.org/postgis/source/postgis-3.3.2.tar.gz  && \
cd /tmp/downloads && \
tar -xvf postgis-3.3.2.tar.gz && \
cd postgis-3.3.2  && ./configure && \
make -j 12 && make install && \
rm /tmp/downloads -rf

USER postgres
