FROM openanolis/anolisos:8.6

LABEL maintainer="mrdrivingduck@gmail.com"

CMD bash

# change to CentOS 8 Stream source, and install EPEL
RUN dnf upgrade -y --refresh && \
    dnf install -y \
        epel-release epel-next-release && \
    dnf install -y glibc-all-langpacks && \
    dnf clean all

# GCC and LLVM (should be 15)
RUN dnf install -y \
        gcc \
        gcc-c++ \
        gdb \
        make \
        cmake \
        clang \
        llvm-devel \
        && \
    dnf clean all

# Dependencies
RUN dnf install -y \
        bison \
        flex \
        fuse-devel \
        gettext \
        krb5-devel \
        libaio-devel \
        libicu-devel \
        libunwind-devel \
        libuuid-devel \
        libxml2-devel \
        libxslt-devel \
        libzstd-devel \
        lz4-devel \
        openldap-devel \
        openssl-devel \
        pam-devel \
        perl-IPC-Run \
        perl-ExtUtils-Embed \
        perl-Test-Simple \
        python3-devel \
        readline-devel \
        tcl-devel \
        xerces-c-devel \
        zlib-devel \
        && \
    dnf clean all

# Tools
RUN dnf install -y \
        wget \
        sudo \
        vim \
        git \
        rpm-build \
        && \
    dnf clean all

# set to empty if GitHub is not barriered
# ENV GITHUB_PROXY=https://ghproxy.com/
ENV GITHUB_PROXY=

ENV ZLOG_VERSION=1.2.14
ENV PFSD_VERSION=pfsd4pg-release-1.2.42-20220419

# install dependencies from GitHub mirror
RUN cd /usr/local && \
    # zlog for PFSD
    wget --no-verbose --no-check-certificate "${GITHUB_PROXY}https://github.com/HardySimpson/zlog/archive/refs/tags/${ZLOG_VERSION}.tar.gz" && \
    # PFSD
    wget --no-verbose --no-check-certificate "${GITHUB_PROXY}https://github.com/ApsaraDB/PolarDB-FileSystem/archive/refs/tags/${PFSD_VERSION}.tar.gz" && \
    # unzip and install zlog
    gzip -d $ZLOG_VERSION.tar.gz && \
    tar xpf $ZLOG_VERSION.tar && \
    cd zlog-$ZLOG_VERSION && \
    make && make install && \
    echo '/usr/local/lib' >> /etc/ld.so.conf && ldconfig && \
    cd .. && \
    rm -rf $ZLOG_VERSION* && \
    rm -rf zlog-$ZLOG_VERSION && \
    # unzip and install PFSD
    gzip -d $PFSD_VERSION.tar.gz && \
    tar xpf $PFSD_VERSION.tar && \
    cd PolarDB-FileSystem-$PFSD_VERSION && \
    sed -i 's/-march=native //' CMakeLists.txt && \
    ./autobuild.sh && ./install.sh && \
    cd .. && \
    rm -rf $PFSD_VERSION* && \
    rm -rf PolarDB-FileSystem-$PFSD_VERSION* && \
    ldconfig

# create default user
ENV USER_NAME=postgres
RUN echo "create default user" && \
    groupadd -r $USER_NAME -g 1000 && \
    useradd -u 1000 -g $USER_NAME $USER_NAME -p '' && \
    usermod -aG wheel $USER_NAME

WORKDIR /home/$USER_NAME

# modify conf
RUN echo "modify conf" && \
    mkdir -p /var/log/pfs && chown $USER_NAME /var/log/pfs && \
    mkdir -p /var/run/pfs && chown $USER_NAME /var/run/pfs && \
    mkdir -p /var/run/pfsd && chown $USER_NAME /var/run/pfsd && \
    mkdir -p /dev/shm/pfsd && chown $USER_NAME /dev/shm/pfsd && \
    touch /var/run/pfsd/.pfsd && \
    chkconfig --add pfsd_env && \
    echo "ulimit -c unlimited" >> /home/postgres/.bashrc && \
    echo "export PGHOST=127.0.0.1" >> /home/postgres/.bashrc && \
    echo "alias pg='psql -h /home/postgres/tmp_master_dir_polardb_pg_1100_bld/'" >> /home/postgres/.bashrc && \
    rm /etc/localtime && \
    cp /usr/share/zoneinfo/UTC /etc/localtime && \
    sed -i 's/vim/vi/g' /root/.bashrc

ENV PATH="/home/postgres/tmp_basedir_polardb_pg_1100_bld/bin:$PATH"

USER $USER_NAME
