name: build and publish docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_image: [ centos7 ]

    steps:

      # Checkout source code
      -
        uses: actions/checkout@v2

      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mrdrivingduck/polardb_pg_devel:${{ matrix.base_image }}
          file: Dockerfile-${{ matrix.base_image }}
          network: "host"
          platforms: linux/amd64,linux/arm64
