name: build and publish docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container_image: [ centos7 ]

    steps:

      # Checkout source code
      -
        uses: actions/checkout@v2

      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build
      -
        name: Build docker image for PolarDB
        run: |
          docker build --network=host                                   \
              -t mrdrivingduck/polardb_pg:${{ matrix.container_image }} \
              -f Dockerfile-${{ matrix.container_image }} .

      # Publish
      -
        name: Push to registry
        run: docker push
