name: build and publish images

on:
  push:
    branches:
      - main
  # trigger testing manually
  workflow_dispatch:

jobs:

  build-and-publish-dev-image-main:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      -
        uses: actions/checkout@v4
      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to the ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push development image with 'latest' tag
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile-devel-ubuntu22.04
          tags: |
            polardb/polardb_pg_devel:ubuntu22.04
            polardb/polardb_pg_devel:latest
            ghcr.io/mrdrivingduck/polardb_pg_devel:ubuntu22.04
            ghcr.io/mrdrivingduck/polardb_pg_devel:latest
          platforms: linux/amd64, linux/arm64

  build-and-publish-dev-image-others:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_image: [ centos7, anolis8, rocky8, rocky9, ubuntu20.04, ubuntu24.04 ]
    steps:
      # Checkout source code
      -
        uses: actions/checkout@v4
      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to the ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push other development images
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile-devel-${{ matrix.base_image }}
          tags: |
            polardb/polardb_pg_devel:${{ matrix.base_image }}
            ghcr.io/mrdrivingduck/polardb_pg_devel:${{ matrix.base_image }}
          platforms: linux/amd64, linux/arm64

  build-and-publish-binary-image:
    runs-on: ubuntu-latest
    needs: build-and-publish-dev-image-main
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to the ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push binary image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile-binary
          tags: |
            polardb/polardb_pg_binary:latest
            ghcr.io/mrdrivingduck/polardb_pg_binary:latest
          platforms: linux/amd64, linux/arm64

  build-and-publish-instance-image:
    runs-on: ubuntu-latest
    needs: build-and-publish-binary-image
    steps:
      # Checkout source code
      - uses: actions/checkout@v4
      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to the ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push instance image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile-local-instance
          tags: |
            polardb/polardb_pg_local_instance:latest
            ghcr.io/mrdrivingduck/polardb_pg_local_instance:latest
          platforms: linux/amd64, linux/arm64
