name: build and publish images

on:
  push:
    branches:
      - main
  # trigger testing manually
  workflow_dispatch:

jobs:
  build-and-publish-dev-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_image: [ centos7 ]

    steps:

      # Checkout source code
      -
        uses: actions/checkout@v3

      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # build devel images (centos7 is the latest tag)
      -
        if: ${{ matrix.base_image == 'centos7' }}
        name: Build and push development image with 'latest' tag
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile-devel-${{ matrix.base_image }}
          network: "host"
          tags: |
            polardb/polardb_pg_devel:${{ matrix.base_image }}
            polardb/polardb_pg_devel:latest
          platforms: linux/amd64, linux/arm64
      # build devel images (other distributions)
      -
        if: ${{ matrix.base_image != 'centos7' }}
        name: Build and push other development images
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile-devel-${{ matrix.base_image }}
          network: "host"
          tags: polardb/polardb_pg_devel:${{ matrix.base_image }}
          platforms: linux/amd64, linux/arm64
  
  # build-and-publish-instance-image:
  #   runs-on: ubuntu-latest
  #   needs: build-and-publish-dev-image

  #   strategy:
  #     matrix:
  #       instance_type: [ single, withrep, htap ]

  #   steps:

  #     # Checkout source code
  #     -
  #       uses: actions/checkout@v3

  #     # Environment preparation
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     # build instance images
  #     -
  #       name: Build and push instance image
  #       uses: docker/build-push-action@v3
  #       with:
  #         push: true
  #         file: Dockerfile-local-instance-${{ matrix.instance_type }}
  #         network: "host"
  #         tags: polardb/polardb_pg_local_instance:${{ matrix.instance_type }}
  #         platforms: linux/amd64, linux/arm64

  build-and-publish-dev-image-for-curvebs:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      -
        uses: actions/checkout@v3

      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # build devel images for Curve
      -
        name: Build and push development image for Curve
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile-devel-curve
          network: "host"
          tags: |
            polardb/polardb_pg_devel:curvebs
          platforms: linux/amd64
