name: build and publish images

on:
  # trigger testing manually
  workflow_dispatch:

jobs:

  build-and-publish-binary-image:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to the ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push binary image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile-binary
          tags: |
            polardb/polardb_pg_binary:latest
            ghcr.io/apsaradb/polardb_pg_binary:latest
          platforms: linux/amd64, linux/arm64

  build-and-publish-instance-image:
    runs-on: ubuntu-latest
    needs: build-and-publish-binary-image
    steps:
      # Checkout source code
      - uses: actions/checkout@v4
      # Environment preparation
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to the ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push instance image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile-local-instance
          tags: |
            polardb/polardb_pg_local_instance:latest
            ghcr.io/apsaradb/polardb_pg_local_instance:latest
          platforms: linux/amd64, linux/arm64
